const SKILL_MAP = {
  // Common abbreviations
  "js": "javascript",
  "ts": "typescript",
  "node": "node.js",
  "nodejs": "node.js",
  "ai": "artificial intelligence",
  "ml": "machine learning",
  "nlp": "natural language processing",
  "cv": "computer vision",
  "ds": "data science",
  "da": "data analysis",
  "devops": "devops",
  "ci/cd": "ci/cd",
  "cicd": "ci/cd",
  "tdd": "tdd",
  "bdd": "bdd",
  "spa": "spa",
  "pwa": "pwa",
  "ssr": "ssr",
  "csr": "csr",
  "ui": "ui",
  "ux": "ux",
  "api": "api",
  "apis": "api",
  "rest api": "rest apis",
  "rest apis": "rest apis",
  "restful": "rest apis",
  "db": "database",
  "sql": "sql",
  "nosql": "nosql",
  "git": "git",
  "github": "git",
  "docker": "docker",
  "k8s": "kubernetes",
  "aws": "aws",
  "gcp": "gcp",
  "azure": "azure",
  "http": "http",
  "https": "https",
  "rest": "rest api",
  "soap": "soap",
  "graphql": "graphql",
  "grpc": "grpc",
  "tcp": "tcp",
  "udp": "udp",
  "json": "json",
  "xml": "xml",
  "yaml": "yaml",
  "yml": "yaml",
  "html": "html",
  "css": "css",
  "scss": "scss",
  "sass": "sass",
  "less": "less",
  // Framework and technology mappings
  "express.js": "express",
  "express": "express",
  "react.js": "react",
  "reactjs": "react",
  "vue.js": "vue",
  "vuejs": "vue",
  "angular.js": "angular",
  "angularjs": "angular",
  "mongodb": "mongodb",
  "mongo": "mongodb",
  "postgresql": "postgresql",
  "postgres": "postgresql",
  "mysql": "mysql",
  "typescript": "typescript",
  "javascript": "javascript",
  "python": "python",
  "java": "java",
  "c++": "c++",
  "c#": "c#",
  "csharp": "c#",
  "php": "php",
  "ruby": "ruby",
  "go": "go",
  "rust": "rust",
  "swift": "swift",
  "kotlin": "kotlin",
  "scala": "scala",
  "dart": "dart",
  "flutter": "flutter",
  "jest": "jest",
  "mocha": "mocha",
  "jasmine": "jasmine",
  "karma": "karma",
  "webpack": "webpack",
  "vite": "vite",
  "parcel": "parcel",
  "rollup": "rollup",
  "babel": "babel",
  "eslint": "eslint",
  "prettier": "prettier"
};

module.exports = function normalizeSkill(skill) {
  const s = skill.toLowerCase().trim();
  return SKILL_MAP[s] || s;
};
